version: "3.8"

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres-pgvector:16-alpine
    networks:
      - selvanet
    entrypoint: docker-entrypoint.sh
    command: [postgres, --max_connections=200]
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS="--auth-host=scram-sha-256"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

networks:
  selvanet:
    external: true
    name: selvanet

volumes:
  postgres-data:
    driver: local
